/**
 * Sola Payments (formerly Cardknox) provider adapter.
 *
 * Supports two transaction surfaces:
 *
 *  1. Card Not Present  — chargeWithToken()
 *     The browser uses the iFields library to tokenize card data into a
 *     single-use token (xToken / SUT). That token is sent to our server
 *     and submitted here via the Sola Transaction API (cc:sale).
 *
 *  2. Card Present      — chargeCloudIM()
 *     A CloudIM-connected terminal processes the card on-device. We push
 *     the sale request to the CloudIM cloud API and it forwards to the reader.
 *
 * Credentials are read from environment variables — no DB IntegrationAccount
 * is required. Set the following in the server .env file:
 *
 *   SOLA_XKEY             — Transaction API key
 *   SOLA_IFIELDS_KEY      — iFields tokenization key (returned to browser)
 *   SOLA_CLOUDIM_KEY      — CloudIM API key (may equal SOLA_XKEY)
 *   SOLA_CLOUDIM_DEVICE_ID — Default terminal device ID
 *   SOLA_WEBHOOK_SECRET   — HMAC secret for webhook verification
 *
 * Sola Transaction API reference:
 *   https://docs.solapayments.com/api/transaction-api
 *
 * CloudIM Developer Guide:
 *   https://docs.solapayments.com/products/cloudim-developer-guide
 */

import { env } from "../../../config/env.js";

const SOLA_GATEWAY_URL = "https://x1.cardknox.com/gatewayjson";
const SOLA_CLOUDIM_URL = "https://api.cloudim.cardknox.com";
const SOFTWARE_NAME    = "APlus Center";
const SOFTWARE_VERSION = "1.0";

/* ─────────────────────────────────────────────────────────────────────────── */
/* Helpers                                                                      */
/* ─────────────────────────────────────────────────────────────────────────── */

function getXKey() {
  const key = env.solaXKey;
  if (!key) {
    const err = new Error("SOLA_XKEY is not configured");
    err.status = 500;
    throw err;
  }
  return key;
}

function getCloudIMKey() {
  return env.solaCloudIMKey || getXKey();
}

/**
 * POST to the Sola gateway and return the parsed response.
 * Throws if xResult is not "A" (Approved).
 */
async function callGateway(params) {
  const body = {
    xKey:             getXKey(),
    xVersion:         "4.5.9",
    xSoftwareName:    SOFTWARE_NAME,
    xSoftwareVersion: SOFTWARE_VERSION,
    ...params
  };

  const response = await fetch(SOLA_GATEWAY_URL, {
    method:  "POST",
    headers: { "Content-Type": "application/json" },
    body:    JSON.stringify(body)
  });

  const data = await response.json().catch(() => ({}));
  return data;
}

/* ─────────────────────────────────────────────────────────────────────────── */
/* 1. Connection test                                                           */
/* ─────────────────────────────────────────────────────────────────────────── */

export async function testConnection() {
  // Sola has no dedicated health endpoint; we verify the key is present and
  // the gateway is reachable by attempting a $0.00 auth-only that will reject
  // cleanly even in sandbox. Any network error surfaces immediately.
  if (!env.solaXKey) {
    const err = new Error("SOLA_XKEY is not configured");
    err.status = 400;
    throw err;
  }
  return { ok: true, message: "Sola Payments key is configured" };
}

/* ─────────────────────────────────────────────────────────────────────────── */
/* 2. iFields key — returned to the frontend so it can load the iFields widget */
/* ─────────────────────────────────────────────────────────────────────────── */

export function getIFieldsKey() {
  const key = env.solaIFieldsKey;
  if (!key) {
    const err = new Error("SOLA_IFIELDS_KEY is not configured");
    err.status = 400;
    throw err;
  }
  return key;
}

/* ─────────────────────────────────────────────────────────────────────────── */
/* 3. Card Not Present charge — uses a single-use token from iFields           */
/* ─────────────────────────────────────────────────────────────────────────── */

/**
 * Charge a card using a single-use token (xToken) generated by iFields.
 *
 * @param {object} opts
 * @param {string} opts.xToken       Single-use token from iFields
 * @param {number} opts.amount       Dollars (e.g. 150.00)
 * @param {string} opts.invoiceNumber Invoice number — used for duplicate detection
 * @param {string} [opts.clientEmail]
 * @param {string} [opts.billingName]
 * @param {string} [opts.billingZip]
 * @param {string} [opts.description]
 * @param {boolean} [opts.saveCard]   If true, instruct Sola to return a reusable xToken
 * @returns {object} Normalised response
 */
export async function chargeWithToken({
  xToken,
  amount,
  invoiceNumber,
  clientEmail,
  billingName,
  billingZip,
  description,
  saveCard = false
}) {
  if (!xToken) {
    const err = new Error("xToken is required for card-not-present charge");
    err.status = 400;
    throw err;
  }
  if (!amount || amount <= 0) {
    const err = new Error("Amount must be greater than 0");
    err.status = 400;
    throw err;
  }

  const params = {
    xCommand:     "cc:sale",
    xToken,
    xAmount:      Number(amount).toFixed(2),
    xInvoice:     invoiceNumber || undefined,
    xDescription: description   || undefined,
    xEmail:       clientEmail   || undefined,
    xBillFirstName: billingName || undefined,
    xBillZip:     billingZip    || undefined,
    xAllowDuplicate: "false"
  };

  const data = await callGateway(params);

  return normaliseResponse(data);
}

/* ─────────────────────────────────────────────────────────────────────────── */
/* 4. Card Present charge — pushes sale to a CloudIM terminal                  */
/* ─────────────────────────────────────────────────────────────────────────── */

/**
 * Initiate a card-present sale on a CloudIM terminal.
 *
 * @param {object} opts
 * @param {string} [opts.deviceId]    Terminal device ID (falls back to env SOLA_CLOUDIM_DEVICE_ID)
 * @param {number} opts.amount        Dollars
 * @param {string} opts.invoiceNumber Invoice number
 * @param {string} [opts.description]
 */
export async function chargeCloudIM({ deviceId, amount, invoiceNumber, description }) {
  const device = deviceId || env.solaCloudIMDeviceId;
  if (!device) {
    const err = new Error("CloudIM device ID is not configured (SOLA_CLOUDIM_DEVICE_ID)");
    err.status = 400;
    throw err;
  }
  if (!amount || amount <= 0) {
    const err = new Error("Amount must be greater than 0");
    err.status = 400;
    throw err;
  }

  const payload = {
    xKey:             getCloudIMKey(),
    xVersion:         "4.5.9",
    xSoftwareName:    SOFTWARE_NAME,
    xSoftwareVersion: SOFTWARE_VERSION,
    xCommand:         "cc:sale",
    xAmount:          Number(amount).toFixed(2),
    xInvoice:         invoiceNumber || undefined,
    xDescription:     description   || undefined,
    xTerminalID:      device
  };

  const response = await fetch(`${SOLA_CLOUDIM_URL}/api/v1/transaction`, {
    method:  "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization:  `Bearer ${getCloudIMKey()}`
    },
    body: JSON.stringify(payload)
  });

  const data = await response.json().catch(() => ({}));
  return normaliseResponse(data);
}

/* ─────────────────────────────────────────────────────────────────────────── */
/* 5. Refund                                                                    */
/* ─────────────────────────────────────────────────────────────────────────── */

/**
 * Refund a previously captured transaction.
 *
 * @param {object} opts
 * @param {string} opts.xRefNum  Original Sola transaction reference number
 * @param {number} opts.amount   Amount to refund in dollars
 */
export async function createRefund({ xRefNum, amount }) {
  if (!xRefNum) {
    const err = new Error("xRefNum is required for refund");
    err.status = 400;
    throw err;
  }

  const data = await callGateway({
    xCommand: "cc:refund",
    xRefNum,
    xAmount:  Number(amount).toFixed(2)
  });

  return normaliseResponse(data);
}

/* ─────────────────────────────────────────────────────────────────────────── */
/* Internal helpers                                                             */
/* ─────────────────────────────────────────────────────────────────────────── */

/**
 * Normalise a raw Sola gateway response into a consistent shape.
 * xResult: "A" = Approved, "D" = Declined, "E" = Error
 */
function normaliseResponse(raw) {
  const approved = String(raw.xResult || "").toUpperCase() === "A";
  const declined = String(raw.xResult || "").toUpperCase() === "D";
  const error    = String(raw.xResult || "").toUpperCase() === "E";

  // Parse masked card number — e.g. "xxxxxxxxxxxx1111" → last4 = "1111"
  const masked = String(raw.xMaskedCardNumber || "");
  const last4  = masked.length >= 4 ? masked.slice(-4) : null;

  // Parse expiry — Sola returns "MMYY" format
  const expRaw   = String(raw.xExp || "");
  const expMonth = expRaw.length >= 2 ? Number(expRaw.slice(0, 2)) : null;
  const expYear  = expRaw.length === 4 ? Number("20" + expRaw.slice(2)) : null;

  return {
    approved,
    declined,
    error,
    xResult:          raw.xResult,
    xStatus:          raw.xStatus,
    xError:           raw.xError    || null,
    xErrorCode:       raw.xErrorCode || null,
    xRefNum:          String(raw.xRefNum || ""),
    xAuthCode:        raw.xAuthCode  || null,
    xToken:           raw.xToken     || null,
    xMaskedCardNumber: masked        || null,
    xCardType:        raw.xCardType  || null,
    xCardBrand:       raw.xCardType  || null,
    cardLast4:        last4,
    cardExpMonth:     expMonth,
    cardExpYear:      expYear,
    xAuthAmount:      raw.xAuthAmount ? Number(raw.xAuthAmount) : null,
    xBatch:           raw.xBatch     || null,
    raw
  };
}
